### PR TITLE
eslint-config-hzdg update

### PR DESCRIPTION
**Pull request by aamorozov**
I'll update the react linter in a separate pull request. Please take a look. The update includes bumping presets to use @babel namespaces, latest versions of eslint/babel/prettier/ava and adding/removing some new/obsolete rules.

### CODE REVIEW

**Comment by johnetrent** [comment]
🎉 🎈 🎊

**Comment by aamorozov** [comment]
`eslint-config-hzdg-react` changes are also ready for you review gentlemen @lettertwo @ryanbagwell

**Comment by aamorozov** [comment]
This should be ready to merge now - we'll need to patch the package version and lock the version of `eslint-config-hzdg` in package.json of `eslint-config-hzdg-react`.

**Comment by aamorozov** [comment]
@lettertwo Makes sense, I've updated the minor versions in both packages

**Pull request merged**
